### ISSUE TITLE
How does this project run on Visual Studio?

### ISSUE THREAD

**Issue by WandQ** [nitrieu/delegated-psi-ca#1]
Hello Ni, congratulations for your new paper on Contact Tracing accepted to Asiacrypt 2020. I have a confusion, how does this project run on Visual Studio? If possible, can you write the process of starting step on Windows or Linux in the readme? Thank you

**Comment by nitrieu** [comment]
@WandQ : Sure, I will provide detailed instructions asap.  A similar README can be found at https://github.com/osu-crypto/MultipartyPSI

**Comment by WandQ** [comment]
Okey , Thank you
